# Generated by Django 2.0.2 on 2018-03-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annId', models.CharField(editable=False, max_length=128, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('text', models.TextField()),
                ('quote', models.TextField()),
                ('ranges', models.TextField()),
                ('tags', models.TextField(default='str')),
                ('permissions', models.TextField()),
                ('user', models.CharField(db_index=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageId', models.CharField(max_length=40)),
                ('title', models.TextField()),
                ('revId', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotatedPage', to='annotator_app.Page'),
        ),
    ]
